### ISSUE TITLE
a[...] = x and a.fill(x) should be the same

### ISSUE THREAD

**Issue by rloewe** [bh107/bohrium#143]
In numpy there is a function called fill (https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.fill.html), which works the same as assign with index `...`.
An example could be:
```
import numpy as np
a = np.zeros(2)
b = np.zeros(2)
a[...] = 5
b.fill(5)
print a == b # True
```

**Comment by madsbk** [comment]
Fixed by a0bef29
