### ISSUE TITLE
bohrium.sqrt(s) breaks how scalars are handles, and forces an upcast of bohrium.arrays

### ISSUE THREAD

**Issue by tblum** [bh107/bohrium#16]
S = np.array(numpy.random.random(10).astype(numpy.float32))
d1 = S/np.sqrt(4.0)

Forces d1 to be of float64 data type where as 
d1 = S/math.sqrt(4.0)

Keeps d1 as float32. Which it should be.

**Comment by tblum** [comment]
The same is true for bohrium.exp() and probably alot of others

**Comment by madsbk** [comment]
This conforms with NumPy. 
In order to have `np.sqrt(4.0)` as `float32` use `np.sqrt(np.float32(4.0))`
