### ISSUE TITLE
Warning about not being able to find hwloc

### ISSUE THREAD

**Issue by fjarri** [bh107/bohrium#17]
OSX 10.10.3

When I run examples, they are executed correctly, but the following warning is shown:

    !! Trying to bind but compiled without required library  !!
    !!            Install hwloc and re-compile               !!
    !!                          OR                           !!
    !! Disable binding by setting ENV_VAR: BH_VE_CPU_BIND=0  !!

I have `hwloc` installed (via homebrew) and tried recompiling Bohrium, but it did not remove the warning. There's no mention of `hwloc` in the `cmake` output. I can set the environment variable, but I am not sure what `hwloc` is used for, and whether I'm losing performance by not enabling it.

**Comment by kenkendk** [comment]
`hwloc` is used to map the physical layout of the machine, to optimize execution in a very hardware optimal fashion (aka NUMA aware). Since Bohrium on OSX does not support multi-threading, issue #19, there is no need for hwloc on OSX yet.
