### ISSUE TITLE
Possible memory leak when indexing with an array

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#180]
I am trying to tweak the performance of the following code:

```python
import numpy as np
import time

try:
    flush = np.flush
except AttributeError:
    flush = lambda: None

def timeit(fun):
    tic = time.time()
    for _ in range(1000):
        res = fun()
    flush()
    toc = time.time()
    print("{}".format(toc-tic))
    return res

if __name__ == "__main__":
    np.random.seed(12345)
    n = (50, 50, 200)
    a = np.arange(np.prod(n)).reshape(n)
    z_indices = np.random.randint(n[2],size=n[:-1])

    def fun1():
         mask2 = np.indices(a.shape)[2] == z_indices[:,:,None]
         return np.asarray(a[mask2].reshape(n[:-1]))

     def fun2():
         mask3x, mask3y = np.indices(a.shape[:-1])
         mask3z = z_indices
         return np.asarray(a[mask3x,mask3y,mask3z])

    timeit(fun1)
    timeit(fun2)
```

It runs very well without Bohrium (and `fun2` is clearly faster by a factor of ~50). When using Bohrium, memory consumption skyrockets (~10GB), and `fun2` loses a lot of performance (slower by a factor of about 100). I know that fancy indexing isn't supported in Bohrium (unfortunately), but the effect of the copy to NumPy shouldn't be that dramatic, especially in memory, right?

By the way, if there is a better way to slice an array along a dimension in Bohrium, I'm happy for any suggestion.

**Comment by madsbk** [comment]
Fixed in PR #307.
Still, fancy indexing is significantly slower in Bohrium compared to NumPy :/
