### ISSUE TITLE
Column-Major for OpenCL

### ISSUE THREAD

**Issue by madsbk** [bh107/bohrium#190]
When it doesn't obstruct fusibility, we should transpose arrays for the OpenCL backend. 
Generally, the GPU backend performs best when accessing by column-major.

**Comment by dionhaefner** [comment]
How big is the impact of this? We are observing quite poor performance on the GPU, and I noticed that execution becomes significantly faster (but still not quite satisfactory) when increasing the workgroup size of the last axis. Is this connected?

**Comment by madsbk** [comment]
Fixed
