### ISSUE TITLE
bh.random.rand() returns NumPy float

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#222]
When simply using ``bh.random.rand()`` (or randint(), or randn(), ...) to create a random scalar float, the returned type is ``np.float64``. This causes e.g. the following code to be handled by NumPy:

```python
import bohrium as bh
a = bh.random.rand()
b = bh.random.rand(10,11,12)
c = a * b
```

**Comment by madsbk** [comment]
As long as NumPy hasn't implemented [`__numpy_ufunc__`](https://docs.scipy.org/doc/numpy-dev/reference/arrays.classes.html#numpy.class.__numpy_ufunc__) we cannot catch NumPy scalars on the left hand side.
Previously, we implemented a HACK to fix this problem but it had undesirable consequences: #22 :(

It looks like `__numpy_ufunc__` is finally getting in NumPy: https://github.com/numpy/numpy/pull/8247

**Comment by dionhaefner** [comment]
Alright. I guess as a workaround I'll just do `a = bh.array(bh.random.rand())`.

**Comment by madsbk** [comment]
NumPy versoin 1.13 now implements [`__numpy_ufunc__`](https://docs.scipy.org/doc/numpy-dev/reference/arrays.classes.html#numpy.class.__numpy_ufunc__).
