### ISSUE TITLE
Exploring CI for testing GPU-VE

### ISSUE THREAD

**Issue by safl** [bh107/bohrium#23]
The following packages can be added to `.travis.yml`:

    fglrx=2:8.960-0ubuntu1 opencl-headers opencl-dev libgl1-mesa-dev``

It compiles just fine, however, it produces the following at runtime:

    $ python ../test/python/numpytest.py --exclude=test_ndstencil.py --exclude=test_benchmarks.py
    *** Testing the equivalency of Bohrium-NumPy and NumPy ***
    Testing test_accumulate.py/accumulate/cumprod
    clGetPlatformIDs
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Error in the initialization of the VEM.
    /home/travis/build.sh: line 41: 13485 Aborted                 python ../test/python/numpytest.py --exclude=test_ndstencil.py --exclude=test_benchmarks.py
    The command "python ../test/python/numpytest.py --exclude=test_ndstencil.py --exclude=test_benchmarks.py" exited with 134.

Which probably makes sense since the resources on travis do not have any GPUs...

But perhaps the GPU-VE could implement some simplified form of execution on CPU?
I guess performance in this setting isn't important. It just needs to be able to run.
Dunno if it makes sense if the testing is not actually done on a GPU?

I don't know of other CI services that actually have GPUs which would be preferable.
But maybe we could roll some integration with MiG or something along those lines...

**Comment by ZhijieWang** [comment]
What about local testing? Though it is not going to be a "standard" environment. 

Another thought, this project may be qualified for some Amazon EC2 credit.

**Comment by tblum** [comment]
GPU-VE now falls back to running on the CPU via opencl if it is possible (i.e. There is an OpenCL platform containing a CPU device), and there is no GPU available.
https://github.com/bh107/bohrium/commit/961eb222b03938dd823109c7de9e6b57f36f6421
