### ISSUE TITLE
When using abs instead of bohrium.abs it syncs to numpy

### ISSUE THREAD

**Issue by rloewe** [bh107/bohrium#231]
When writing `abs(bohrium_array)` it syncs to NumPy, this could be fixed by implementing the `__abs__` function on the `bohrium.nd_array` class. It might also be the case for other functions so here is [a list of standard operator functions](https://docs.python.org/2/library/operator.html).

**Comment by madsbk** [comment]
In master, `__abs__` should be implemented.

Running the following code using `BH_OPENMP_PROF=1 python -m bohrium test.py` doesn't generate any syncs to numpy on my machine.
```python 
import numpy as np
a = np.arange(-10, 10)
b = abs(a)
c = np.abs(a)
```
Please try to run it on your machine.
