### ISSUE TITLE
Feature request: Bohrium ipython magic

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#242]
It would be great if Bohrium supplied an ipython magic, so you could do the folllwing in a Jupyter notebook cell:

```python
%%bohrium
import foo
foo.run()
```

which would have the same effect as running `foo` with `python -m bohrium`. That way you could "bohriumify" arbitrary notebook cells.

**Comment by omegahm** [comment]
I'll look into if we want to supply this with the build/install of Bohrium, but for now, you can create a file called `50-bohrium.py` in your `~/.ipython/profile_default/startup` directory, with this content:

```python
from IPython.core.magic import register_cell_magic

@register_cell_magic
def bohrium(line, cell):
    import sys
    import numpy
    import bohrium

    sys.modules['numpy_force'] = numpy
    sys.modules['numpy'] = bohrium
    sys.modules['numpy.random'] = bohrium.random
    sys.modules['numpy.linalg'] = bohrium.linalg

    exec(cell, globals(), locals())

    return None

del bohrium
```

Then restart your Jupyter server and now you should be able to run:

```python
%%bohrium
print numpy.arange(10)
```

and then get `[0 1 2 3 4 5 6 7 8 9]` from Bohrium (verify e.g. by running `print numpy`)

**Comment by dionhaefner** [comment]
Works great, thanks!

**Comment by omegahm** [comment]
Once #243 has gone through testing, if the compiler detects `jupyter` on your system, it will write the startup-file itself. It will never overwrite it, so you might want to delete it and then recompile Bohrium (so you get the version that uses the new overwrite method in Bohrium from the same pull-request)

**Comment by dionhaefner** [comment]
Looks like I can't get anything out of the cell in this case? I was hoping I could do something like

```python
%%bohrium
import foo
res = foo.run()
```

and then, in the next cell,

```python
import matplotlib.pyplot as plt
plt.imshow(res)
```

like with the `%%cython` cell magic.

**Comment by omegahm** [comment]
I'm no expert in Jupyter, so I'll have to look into that. 😆

**Comment by dionhaefner** [comment]
Sure. If it turns out to be too complicated for now, a line magic that applies to the whole notebook would be fine, too (a bit like `%matplotlib inline`), so you could do

```python
%bohrium
```

at the start of your notebook, which replaces numpy with bohrium throughout the whole session (and which propagates through imports).

**Comment by omegahm** [comment]
Can you try 

```python
from IPython.core.magic import register_cell_magic

@register_cell_magic
def bohrium(line, cell):
    import bohrium
    bohrium.overwrite_numpy()

    # Code must end with \n
    code = cell if cell.endswith("\n") else cell + "\n"
    exec(code, globals(), locals())

    excludes = set(["excludes", "code", "cell", "line"])
    try:
        # Python 2.x
        for key, value in locals().iteritems():
            if key not in excludes:
                print(key, "=", value)
                globals()[key] = value
    except:
        # Python 3.x
        for key, value in locals().items():
            if key not in excludes:
                globals()[key] = value

    return

del bohrium
```

instead? It should take all variables defined in the cell and make them global.

**Comment by dionhaefner** [comment]
That's more like it, but now bohrium leaks into the rest of the notebook. So if I do

```python
%%bohrium
pass
...
```

and then

```python
import numpy as np
print(np)
print(bohrium)
```

it gives

> <module 'bohrium' from '...'>
> <module 'bohrium' from '...'>

I think it would be more convenient to keep that from happening by restoring `sys.modules` after the cell code was executed, so you can clearly separate bohrium cells from the rest of the application (and go back to numpy-only mode).

Either way, that's a nice working solution!

**Comment by omegahm** [comment]
Ah, add `np` and `bohrium` to the list of excludes

**Comment by omegahm** [comment]
You might be right about the `sys.modules` as well.

**Comment by dionhaefner** [comment]
Adding to the excludes doesn't help, because `sys.modules` stays overwritten.

**Comment by omegahm** [comment]
Yes, I see. I think I'll try something else with the `bohrium.overwrite`, maybe making it an decorator and then resetting `sys.modules` afterwards.

**Comment by dionhaefner** [comment]
Yes, that should work. Another thing that just came to my mind: This would probably produce really weird bugs if you decided to use e.g. `cell` as a variable name in your script, so maybe we should prefix all the local variables in the ipython magic with `__` or something :wink:

**Comment by omegahm** [comment]
I think the newest version of the pull-request ( #243 ) fixes _everything_!

**Comment by dionhaefner** [comment]
Awesome, thanks! :smile:
