### ISSUE TITLE
Feature request: Parallel TDMA solver extmethod

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#248]
For our application we need a function that is able to solve about 10^6 tridiagonal matrix equations in reasonable time (where each matrix consists of ~300 elements). Since the number of matrices is much higher than the size of each system, it should be pretty efficient to solve them in parallel using the naive [Thomas algorithm](https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm) on all matrices at the same time (this should also perform better than e.g. LAPACK's `dgtsv`). Currently, we implement it like that:

```python
def solve_tridiag(a, b, c, d):
    """
    Solves a tridiagonal matrix system with diagonals a, b, c and RHS vector d.
    """
    assert a.shape == b.shape and a.shape == c.shape and a.shape == d.shape
    n = a.shape[-1]
    x, cp, dp = np.zeros_like(a), np.zeros_like(a), np.zeros_like(a)

    # initialize c-prime and d-prime
    cp[...,0] = c[...,0]/b[...,0]
    dp[...,0] = d[...,0]/b[...,0]

    # solve for vectors c-prime and d-prime
    for i in xrange(1, n):
        m = b[...,i] - cp[...,i-1] * a[...,i]
        fxa = 1.0 / m
        cp[...,i] = c[...,i] * fxa
        dp[...,i] = (d[...,i]-dp[...,i-1]*a[...,i]) * fxa
    x[...,n-1] = dp[...,n-1]
    for i in xrange(n-2, -1, -1):
        x[...,i] = dp[...,i] - cp[...,i]*x[...,i+1]
    return x
```

This way, we can actually solve all of the equations in parallel, but it still requires an explicit loop across one axis, which makes the code perform suboptimal. It would thus be great to have a built-in method for solving many tridiagonal systems in Bohrium that is implemented in C, so we don't have to carry the overhead of the Python loop.

I'd be happy to do the implementation myself if necessary - in that case I would just need a quick explanation on how to do that.

**Comment by madsbk** [comment]
Fixed by #256
