### ISSUE TITLE
No warning on strange/invalid stack setup 

### ISSUE THREAD

**Issue by tblum** [bh107/bohrium#25]
When using an "invalid" stack definition like the following no warning is given, and it is not clear what setup of components is used. A warning would be nice. But actually I think it should halt with an error.

Example with multiple `bcexp`:
```
[stack_gpu]
type = stack
stack_gpu = bcexp
bcexp = dimclean
bcexp = greedy
greedy = node
node = gpu
gpu = cpu
```

**Comment by omegahm** [comment]
@madsbk Your new ini-format will solve this, right?

**Comment by madsbk** [comment]
Yup :)
