### ISSUE TITLE
Some test can not via numpytest.py using the GPU-VE

### ISSUE THREAD

**Issue by tblum** [bh107/bohrium#27]
The problematic tests include `test_gauss`, `test_gauss_20x20`, `test_jacobi`, and `test_jacobi_fixed` - depending on execution platform.

Observations:
The subprocess started from `numpytest.py` exits with exit code -11. This can be verified by using `subprocess.check_output(cmd)` in stead of `subprocess.Popen(cmd).communicate()`

So multiple instances of bohrium enabled python are running - main process and sub processes. Do we support this in bohrium?

When attaching `gdb` to the process on the commandline. `gdb` is attached to the `numpytest.py` process, end not the subprocess, which is the one failing. How can `gdb` be attached?

`valgrind` can be attached to the subprocess by manipulating `sys_exec` (l227) in `numpytets.py`. `valgrind` shows no errors.

`gdb` can not be attached in this manner. Any ideas why?

@madsbk, @safl do you have any ideas/input?

**Comment by madsbk** [comment]
We used to support multiple instances of Bohrium executions at least :)
E.g., the CPU-VE and fuse cache avoids race conditions when reading/writing cache files.

**Comment by tblum** [comment]
Any ideas on how to debug - cause i am at a loss. I can not produce the error without running thrue numpytest.py. When running thru numpytest.py i do not know how to attach a debugger.

**Comment by madsbk** [comment]
Fixed in #140
