### ISSUE TITLE
LAPACK's dgesv gives wrong result when called with sliced arrays

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#287]
Consider the following code:

```python
import numpy as np
import bohrium as bh
import bohrium.lapack
import scipy.linalg.lapack

a = np.random.rand(10,10)
b = bh.array(a)
rhs = np.random.rand(10)
rhs_b = bh.array(rhs)
sol_np = scipy.linalg.lapack.dgesv(a[1:, 1:],rhs[1:])[2]
print(sol_np, np.allclose(np.dot(a[1:, 1:], sol_np), rhs[1:]))
sol_bh = bohrium.lapack.gesv(b[1:, 1:], rhs_b[1:])
print(sol_bh, np.allclose(np.dot(a[1:, 1:], sol_bh), rhs[1:]))
```

This gives correct results for scipy, but wrong results for bohrium. If I remove the `[1:, 1:]` slices, everything matches.

**Comment by omegahm** [comment]
I think this might just be because we don't check the first matrix if it's contiguous in memory. I'll look into this.

**Comment by Athas** [comment]
I had a similar bug with exactly that cause: https://github.com/HIPERFIT/futhark/issues/310
