### ISSUE TITLE
Missing function: bohrium.isfinite()

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#313]
```python
import bohrium as bh

a = bh.random.rand(10)
a[5] = bh.nan
print(bh.isfinite(a))
```

is handled by NumPy.

**Comment by omegahm** [comment]
This should be straightforward, as we already have `BH_ISINF` as a byte code. I'll look into getting a `BH_ISFINITE`, which will return `True` for all none-NaN and none-infinite values.

**Comment by omegahm** [comment]
`BH_ISNAN` also exists. So `not bh.isnan(a)` should do what you want?

**Comment by dionhaefner** [comment]
As far as my understanding goes, `np.isfinite(a)` is practically equal to `np.logical_not(np.logical_or(np.isnan(a), np.isinf(a)))´.

**Comment by omegahm** [comment]
Oh, yeah, that's true, you want it to catch both isnan and isinf.
