### ISSUE TITLE
Disable fuse cache for fusers running in O(n)

### ISSUE THREAD

**Issue by tblum** [bh107/bohrium#33]
Does it make any sense to have the fuse cache enabled for fusers that run in O(n), where n is number of instructions? 
We have two fusers that run in O(n): singleton and topological. 
The the fuse cache hash algorithm runs in O(n). So is there any reason to cache the fused kernels? Writing and reading files on networked file systems are slow.

It would make sense to do some tests, and change the default setting.
@madsbk @safl

**Comment by madsbk** [comment]
The topological fuse runs in O(n^2) since the fusibility check is O(n) but singleton is obviously O(n).

The reading and writing of cache files only happens when Bohrium starts and stops, no files are written doing an execution.

But yeah, it is always nice to get some empirical data :)
