### ISSUE TITLE
Memory leak when setting an array with more than 3 dimensions

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#340]
Example:

```python
import bohrium as bh

a = bh.zeros((10,10,10,10))
b = 1.

def foo(a,b):
    a[...] = b
    bh.flush()

while True:
    foo(a,b)
```

This leaks memory:

![bh_leak](https://cloud.githubusercontent.com/assets/11994217/26258377/c6904e2a-3cc4-11e7-8a67-54b1bfd17a30.png)

This does not:

```python
import bohrium as bh

a = bh.zeros((10,10,10))
b = 1.

def foo(a,b):
    a[...] = b
    bh.flush()

while True:
    foo(a,b)
```

![bh_noleak](https://cloud.githubusercontent.com/assets/11994217/26258399/e7a1f8e8-3cc4-11e7-8618-5a25ccaae712.png)

Don't ask me how I found out.

**Comment by madsbk** [comment]
`python`

**Comment by madsbk** [comment]
Please check if PR #352 fixes the leak.

Now the global refcount doesn't go to infinity at least :)
```Python
import bohrium as bh
import sys

a = bh.zeros((10,10,10, 10, 10))
b = 1.

def foo(a,b):
    a[:] = b
    bh.flush()
    print sys.gettotalrefcount()

while True:
    foo(a,b)
```

**Comment by dionhaefner** [comment]
Seems fixed to me. There's still a memory leak somewhere in my code, but I'll open a separate issue as soon as I have tracked it down.
