### ISSUE TITLE
Is this project 64bit only? (Linux)

### ISSUE THREAD

**Issue by productivememberofsociety666** [bh107/bohrium#35]
Quick question: Is your project expected to work on 32bit Linux systems? It seems to compile fine for me, but I get this error when I try to do anything with it:
````
>>> bohrium.zeros(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ndarray.pyx", line 74, in ndarray.fix_returned_biclass.inner (bohrium/build/bridge/npbackend/ndarray.c:1651)
  File "bohrium/ufunc.py", line 85, in assign
    get_base(ary)._data_bhc2np()
TypeError: get_bhc_data_pointer(ary) should return a Python integer that represents a memory address
````
I added some code that checks if the data in question is a long integer instead and it turns out that it is.
I remember being unable to use this project on another 32bit system a while back, so is that the ultimate cause here?

**Comment by madsbk** [comment]
Yes, the NumPy bridge (frontend) appear not to work with 32bit. 
I must admit that I never tried running Bohrium on a 32bit system. But when I think about now, it makes sense. On a 32bit system, a Python scalar is 32bit and not 64bit thus the address spaces translation will fail.

**Comment by productivememberofsociety666** [comment]
Thank you for the quick response. This should be documented somewhere in my opinion.

Would it work if I ran it on Python 3? I'd try it myself if I got it to work with Python 3, but that's another issue...
