### ISSUE TITLE
C# NumCIL NdArray[range]: Incorrect 'Range' behavior (last or count?)

### ISSUE THREAD

**Issue by buhbuhtig** [bh107/bohrium#356]
Incorrect 'Range' behavior:
`var testNdArray = new NdArray<int>(new[] {1,2,3,4,5 }); // Count == 5`
`var range = new Range(first:0, last:4, stride:1); // 'Count' == 5`
`var newNdArray = testNdArray[range]; // newNdArray should be the same as testNdArray`
`Console.WriteLine(newNdArray.Count());`
-> 4 (wrong!)

The possible problem is with the following line (bohrium/bridge/NumCIL/NumCIL/NdArray.cs), **range.Last - 1**:

`last = range.Last <= 0 ? (this.Shape.Dimensions[dim].Length - 1) + range.Last : range.Last - 1;`

**Comment by madsbk** [comment]
We do not support .NET anymore but hopefully we will support it again when we find the manpower.
