### ISSUE TITLE
Crash when printing quasi-scalar arrays using format string

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#405]
```python
import bohrium as np

a = np.array([1])
print("{:.2f}".format(np.sum(a)))
```

Works with NumPy, gives `ValueError` with Bohrium:

```
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by omegahm** [comment]
You get the same issue in Numpy if trying to print an array this way. This is because Bohrium always shows stuff, even 0-d arrays (or numbers, if you like), as arrays.

I think one option here, could be to have bohrium represent 0-d arrays as what's actually in them. That is, have 

```python
np.sum(np.arange(10)) # => 45
bh.sum(bh.arange(10)) # => array(45)
```

both output the same representation.

**Comment by dionhaefner** [comment]
Yes, I think that would be preferable, and less surprising to NumPy users.

**Comment by omegahm** [comment]
I've written a test, that needs to pass:

```python
import util

class test_single_repr:
    def init(self):
        cmd = "a = M.array([1]).sum();"
        yield cmd

    def test_repr(self, cmd):
        cmd += "res = a.__repr__()"
        return cmd

    def test_str(self, cmd):
        cmd += "res = a.__str__()"
        return cmd


class test_array_repr:
    def init(self):
        cmd = "a = M.arange(10);"
        yield cmd

    def test_repr(self, cmd):
        cmd += "res = a.__repr__()"
        return cmd

    def test_str(self, cmd):
        cmd += "res = a.__str__()"
        return cmd
```

Right now it works with the array representation, but not with the single representation. That is, if the function returns a single value, Bohrium will still show it as an array, while NumPy will show it as an integer (or possibly float).

**Comment by omegahm** [comment]
The reason it fails, might be linked to this:

```python
type(np.array([1]))       # => <type 'numpy.ndarray'>
type(np.array([1]).sum()) # => <type 'numpy.int64'>

type(bh.array([1]))       # => <type 'bohrium.ndarray'>
type(bh.array([1]).sum()) # => <type 'bohrium.ndarray'>
```
