### ISSUE TITLE
locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by ale93111** [bh107/bohrium#409]
Tried to run the latest stable build and I got this error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

as mentioned in this thread "export LC_ALL=C" solved the issue with the with boost::filesystem  
https://svn.boost.org/trac10/ticket/4688

**Comment by omegahm** [comment]
As mentioned in the linked comment, you should just use `LC_ALL=C`.
