### ISSUE TITLE
Make install tries to find files in lib instead of lib64 on 64-bit Fedora

### ISSUE THREAD

**Issue by Ektorus** [bh107/bohrium#42]
When compiling Bohrium I get the following error:
CMake Error at bridge/npbackend/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/ulrik/git/bohrium/build/bridge/npbackend/lib".
Call Stack (most recent call first):
  cmake_install.cmake:70 (include)

Makefile:66: recipe for target 'install' failed
make: *** [install] Error 1

My system configuration is Fedora 64-bit:
Linux Ulrik-LAP-2012 4.1.3-100.fc21.x86_64 #1 SMP Wed Jul 29 18:59:46 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

This bug was fixed in ad19964a9a649041dc1afa011b0967b4b12ed7e6, but has been reintroduced in 70fb72a81c86850a7d4255b3fc0b7a253cbd9623.

**Comment by madsbk** [comment]
Fixed in b419aac
