### ISSUE TITLE
Cannot build Bohrium with Release flags on GCC 7.2.0

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#447]
I tried to build Bohrium on Ubuntu 17.10, which uses GCC 7.2.0 as default compiler. Everything works fine with Debug flags, but when I switch to Release build, I get

```
ImportError: /home/dion/.local/lib/libbhc.so: undefined symbol: _ZNSaIlEC1Ev
```

upon importing `bohrium` (build runs fine).

**Comment by omegahm** [comment]
I just tried compiling it in a 17.10 Docker image. A lot of things break. For example OpenCV cannot compile version `3.2.0`, but must be updated to `3.3.0`. clBLAS doesn't compile in Bohrium because of a missing template argument in `cl.hpp`, which can be ignored, but then we must add additional compiler arguments (e.g. `-Wno-error=ignored-attributes`). 

Haven't gone further than this at the moment.

**Comment by omegahm** [comment]
I can build in the Docker image while setting `-DUSE_WERROR=OFF`. Then I get the same error as @dionhaefner when trying to do `import bohrium`. This is a problem in both python2.7 and python3.6.

**Comment by omegahm** [comment]
It seems that removing the `-O3` from the `CMAKE_CXX_FLAGS_RELEASE` does the trick. 😕

**Comment by omegahm** [comment]
If I do a `scanelf -l -s _ZNSaIlEC1Ev | grep _ZNSaIlEC1Ev` with debug on I get 

```
ET_DYN _ZNSaIlEC1Ev /usr/lib/libbhxx.so
ET_DYN _ZNSaIlEC1Ev /usr/lib/libbhc.so
ET_DYN _ZNSaIlEC1Ev /usr/lib/libbh.so
```

indicating that the symbol is present in those three libraries, but with release I only get

```
ET_DYN _ZNSaIlEC1Ev /usr/lib/libbhc.so
```

So somehow the symbol is being removed from `libbh.so` and `libbhxx.so`.

**Comment by dionhaefner** [comment]
Sound like [something like this](https://stackoverflow.com/questions/5486045/gcc-optimization-results-in-undefined-symbol-at-runtime) could be going on?

**Comment by omegahm** [comment]
`_ZNSaIlEC1Ev` demangled is `std::allocator<long>::allocator()`. That doesn't really help a lot, mostly since we no where use this allocator directly.

**Comment by dionhaefner** [comment]
As a workaround: Bohrium compiles and runs fine with GCC 6. On Ubuntu 17.04, you can get GCC 6 via

```
sudo apt install gcc-6 g++-6
```

and build Bohrium with

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-6
```
