### ISSUE TITLE
locale-related runtime error?

### ISSUE THREAD

**Issue by allefeld** [bh107/bohrium#499]
This one is strange. When I enter the lines

```
import bohrium as np
z = np.zeros((100, 100))
```

in a fresh Python3 or IPython 3 shell, it crashes with the error message

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)
```

This does not happen with `numpy as np`, and I don't have any other locale-related problems with Python.

Python 3.6.4 from Anaconda 3 (Dec 21 2017), bohrium v0.8.9 installed via conda, on a Debian stretch system.

**Comment by dionhaefner** [comment]
This issue is documented in #409
