### ISSUE TITLE
Suggestion: blacklist the CPU OpenCL device on macOS

### ISSUE THREAD

**Issue by athas** [bh107/bohrium#511]
After the university bought me a Mac, I have really come to appreciate the quality engineering that went into these machines.  One aspect of this attention to detail is the default (and only) OpenCL implementation, which presents various devices, including a CPU device and one or more GPU devices.  From what I can determine, this CPU device *refuses* to launch OpenCL workgroups that contain more than one thread (if the kernel contains barriers at all), or more than 128 threads (if the kernel has no barriers), although when queried, the device will cheerfully claim to support groups up to 1024 threads.

Unfortunately, this CPU device is first in the device list, so Bohrium will pick it by default, and soon crash.  I suggest never picking (by default, anyway) the CPU device when running with the "Apple" OpenCL platform.

**Comment by omegahm** [comment]
@madsbk This is the issue I run into when trying to run `BH_STACK=opencl python -m bohrium --info`. I need `BH_OPENCL_DEVICE_TYPE=gpu` in order for it to work. This is not always the case, ie. I can run different Bohrium program with the OpenCL stack without problems, except the `info` above.

I suggest we do what @athas suggest, and remove the CPU device with the Apple platform from the list if `auto` is chosen.
