### ISSUE TITLE
Error -49 when running on OpenCL

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#514]
Since updating Bohrium, I cannot run Veros on OpenCL anymore (even though the Bohrium unit tests pass). Both on my PC [and on Travis](https://travis-ci.org/dionhaefner/veros/jobs/345992873) runs fail abruptly with 

```
Error code: -49
terminate called after throwing an instance of 'cl::Error'
  what():  clSetKernelArg
Aborted (core dumped)
```

I could not isolate the problem; the last kernel that is written looks harmless:

```C
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
#include <kernel_dependencies/complex_opencl.h>
#include <kernel_dependencies/integer_operations.h>

__kernel void execute_6819782572291348866(__global long* __restrict__ a1, __global double* __restrict__ a2, __global double* __restrict__ a3, ulong vo0, ulong vs0_0, ulong vs0_1, ulong vs0_2, ulong vo1, ulong vs1_0, ulong vs1_1, ulong vs1_2, ulong vo2, ulong vs2_0, ulong vs2_1, ulong vs2_2) {
    // The IDs of the threaded blocks: 
    const uint g0 = get_global_id(0); if (g0 >= 34) { return; } // Prevent overflow
    const uint g1 = get_global_id(1); if (g1 >= 46) { return; } // Prevent overflow
    const uint g2 = get_global_id(2); if (g2 >= 14) { return; } // Prevent overflow

    {const ulong i0 = g0;
        {const ulong i1 = g1;
            {const ulong i2 = g2;
                double t0;
                const ulong idx1 = (vo1 +i0*vs1_0 +i1*vs1_1 +i2*vs1_2);
                const ulong idx0 = (vo0 +i0*vs0_0 +i1*vs0_1 +i2*vs0_2);
                const ulong idx2 = (vo2 +i0*vs2_0 +i1*vs2_1 +i2*vs2_2);
                t0 = a1[idx1];
                a2[idx0] = a3[idx2] * t0;
            }
        }
    }
}
```

The weird thing is that everything works fine when installing Bohrium via `pip`. Only the version I build from source seems to have this problem. You can see our base Dockerfile [here](https://github.com/dionhaefner/veros/blob/fix-tests-again/base.dockerfile). If you want to reproduce the problem, you can build [this Dockerfile](https://github.com/dionhaefner/veros/blob/fix-tests-again/testing.dockerfile), execute it, and run

```bash
veros copy-setup acc --to /tmp
cd /tmp/acc
BH_STACK=opencl python acc.py -b bohrium
```

**Comment by madsbk** [comment]
I suspect it is because of a bug in the last merged pull request. I'm looking into it.

**Comment by madsbk** [comment]
@dionhaefner: Could you try again with master? 
I hope #515 fixed the bug

**Comment by dionhaefner** [comment]
Seems to work now, thanks!

**Comment by madsbk** [comment]
@dionhaefner: Could you try again with master?
I hope #521 fixed the bug

**Comment by dionhaefner** [comment]
Not quite there yet. The following segfaults on Python 3 only:

```python
import bohrium as bh

arr = bh.random.rand(100, 100)
masked = bh.ma.masked_where(arr > 0.5, arr)
mean = masked.mean(axis=0)
bh.where(~masked.mask, mean[bh.newaxis, ...], arr)
```

**Comment by madsbk** [comment]
@dionhaefner: what about now? :)

**Comment by dionhaefner** [comment]
Works! Great job
