### ISSUE TITLE
OpenCL select GPU Device vs. GPU Platform 

### ISSUE THREAD

**Issue by nutrik** [bh107/bohrium#519]
How to run separate Bohrium powered applications on several similar GPUs simultaneously and on one node? It seems impossible to choose a GPU and assign an individual run to each GPU. The only environment variable I have found is `BH_OPENCL_PLATFORM_NO`, but both GPUs are under the same Platform. So when I run a second copy of application then both processes are killed with termination error:
```
pyopencl-invoker-cache-v1: in mem cache hit [key=1fc007e39493fed6f5e0c45672144578c269a48fd12e4bc28dc2ce3b7c1dc753]
Error code: -4
terminate called after throwing an instance of 'cl::Error'
  what():  clEnqueueNDRangeKernel
```
For details see also: #https://github.com/dionhaefner/veros/issues/43

**Comment by omegahm** [comment]
At the moment Bohrium will only select the first GPU (this is done in https://github.com/bh107/bohrium/blob/master/ve/opencl/engine_opencl.cpp#L34-L82)

We could modify this, so that we can index into the device vector with environment variables as well. What do you think @madsbk?

**Comment by omegahm** [comment]
With #526 this should be closed. You can use `BH_OPENCL_DEVICE_NUMBER=0` and `BH_OPENCL_DEVICE_NUMBER=1` to choose the different device.

**Comment by nutrik** [comment]
@omegahm Thanks!
