### ISSUE TITLE
Mac: Bohrium randomly cannot find kernel_dependencies

### ISSUE THREAD

**Issue by Baekalfen** [bh107/bohrium#551]
It seems like every other time I run Bohrium, it is unable to find the right dependencies. I'm suspecting, this could be a caching issue.

I've verified the `config.ini` file, and it does reference the correct directory for OpenCL `compiler_flg`.

This is what it looks like:

    $ BH_OPENCL_PROF=1 BH_STACK=opencl BH_OPENCL_VERBOSE=1 python -m bohrium benchpress/benchpress/benchmarks/montecarlo_pi/python_numpy/montecarlo_pi.py "4000000*100"
    ...
    Write source "/var/folders/mx/rshb9_qn33d74jf3gyq19_j00000gn/T/bh_e012/src/de3de0e1a96a0c5d_56fd34109944b3ca.cl"
    Error code: -11
    Error building:
    <program source>:4:10: fatal error: 'kernel_dependencies/complex_opencl.h' file not found
    #include <kernel_dependencies/complex_opencl.h>

The issue doesn't appear in Ubuntu 18.04, although it is compiled from the same source.

**Comment by madsbk** [comment]
Could you attach your config.ini file

**Comment by Baekalfen** [comment]
# Bohrium version: 0.9.1

    ##########################################################################
    # Stack configurations, which are a comma separated lists of components. #
    # NB: 'stacks' is a reserved section name and 'default'                  #
    #     is used when 'BH_STACKS' is unset.                                 #
    #     The bridge is never part of the list                               #
    ##########################################################################
    [stacks]
    default      = bcexp_cpu, bccon, node, openmp
    openmp       = bcexp_cpu, bccon, node, openmp
    opencl       = bcexp_gpu, bccon, node, opencl, openmp
    cuda         = bcexp_gpu, bccon, node, cuda, openmp
    proxy_openmp = bcexp_cpu, bccon, proxy, node, openmp
    proxy_opencl = bcexp_cpu, bccon, proxy, node, opencl, openmp
    proxy_cuda   = bcexp_cpu, bccon, proxy, node, cuda, openmp

    ############
    # Managers #
    ############
    [node]
    impl = /Users/mads/.bin/bohrium/lib/libbh_vem_node.dylib
    timing = false

    [proxy]
    address = localhost
    port = 4200
    impl = /Users/mads/.bin/bohrium/lib/libbh_vem_proxy.dylib
    libs = 


    #############################
    # Filters - Helpers / Tools #
    #############################
    [pprint]
    impl = /Users/mads/.bin/bohrium/lib/libbh_filter_pprint.dylib

    ###################################
    # Filters - Bytecode transformers #
    ###################################
    [bccon]
    impl = /Users/mads/.bin/bohrium/lib/libbh_filter_bccon.dylib
    collect = true
    stupidmath = true
    muladd = true
    reduction = false
    find_repeats = false
    timing = false
    verbose = false

    [bcexp_cpu]
    impl = /Users/mads/.bin/bohrium/lib/libbh_filter_bcexp.dylib
    powk = true
    sign = false
    repeat = false
    reduce1d = 0
    timing = false
    verbose = false

    [bcexp_gpu]
    impl = /Users/mads/.bin/bohrium/lib/libbh_filter_bcexp.dylib
    powk = true
    sign = false
    repeat = false
    # Transform 1d reductions into 2d reductions by array reshaping
    reduce1d = 32000
    timing = false
    verbose = false

    [noneremover]
    impl = /Users/mads/.bin/bohrium/lib/libbh_filter_noneremover.dylib
    timing = false
    verbose = false

    ###########
    # Engines #
    ###########
    [openmp]
    impl = /Users/mads/.bin/bohrium/lib/libbh_ve_openmp.dylib
    verbose = false
    # Profiling statistics
    prof = false
    prof_filename =
    # Write a Graphviz graph for each kernel
    graph = false
    # Directory for temporary files (e.g. /tmp/). Default: `boost::filesystem::temp_directory_path()`
    tmp_dir =
    # Directory for cache files (persistent between executions). Default: the empty string, which disable the cache
    cache_dir = /Users/mads/.bin/bohrium/var/bohrium/cache
    # Maximum number of cache files to keep in the cache dir (use -1 for infinity)
    cache_file_max = 50000
    # Set the size limit of malloc cache in percentage of total system memory.
    malloc_cache_limit = 80
    # The command to execute the compiler where {OUT} is replaced with the binary file output, {IN} with the source file,
    # and {CONF_PATH} with the path to this config file
    compiler_cmd = "/Library/Developer/CommandLineTools/usr/bin/cc -x c -dynamiclib -arch x86_64 -Wno-expansion-to-defined -O3 -Wno-pass-failed -march=native -Werror -I/Users/mads/.bin/bohrium/share/bohrium/include -lm -L/Users/mads/.bin/bohrium/lib -lbh {IN} -o {OUT}"
    # JIT compile options
    compiler_openmp = false
    compiler_openmp_simd = false
    # List of extension methods
    libs = /Users/mads/.bin/bohrium/lib/libbh_blas.dylib, /Users/mads/.bin/bohrium/lib/libbh_lapack_le.dylib, /Users/mads/.bin/bohrium/lib/libbh_lapack_lsp.dylib, /Users/mads/.bin/bohrium/lib/libbh_lapack_sesvp.dylib, /Users/mads/.bin/bohrium/lib/libbh_lapack_gesvp.dylib, /Users/mads/.bin/bohrium/lib/libbh_lapack_ele.dylib, /Users/mads/.bin/bohrium/lib/libbh_lapack_elsp.dylib, /Users/mads/.bin/bohrium/lib/libbh_lapack_egsep.dylib, /Users/mads/.bin/bohrium/lib/libbh_lapack_egnep.dylib
    # The pre-fuser to use ('none' or 'lossy')
    pre_fuser = lossy
    # List of instruction fuser/transformers
    fuser_list = greedy, collapse_redundant_axes
    # Number of edges in the fusion graph that makes the greedy fuser use the `reshapable_first` fuser instead
    greedy_threshold = 10000
    # *_as_var specifies whether to hard-code variables or have them as variables
    index_as_var = true
    strides_as_var = true
    const_as_var = true
    # Monolithic combines all blocks into one shared library rather than a block-nest per shared library
    monolithic = false

    [opencl]
    impl = /Users/mads/.bin/bohrium/lib/libbh_ve_opencl.dylib
    verbose = false
    # Profiling statistics
    prof = false
    prof_filename =
    # Write a Graphviz graph for each kernel
    graph = false
    # Directory for temporary files (e.g. /tmp/). Default: `boost::filesystem::temp_directory_path()`
    tmp_dir =
    # Directory for cache files (persistent between executions). Default: the empty string, which disable the cache
    cache_dir = /Users/mads/.bin/bohrium/var/bohrium/cache
    # Maximum number of cache files to keep in the cache dir (use -1 for infinity)
    cache_file_max = 50000
    # Set the size limit of malloc cache in percentage of total GPU memory.
    malloc_cache_limit = 90
    # Device type can be one of 'auto', 'gpu', 'cpu', 'accelerator', or 'default'
    device_type = gpu
    # Device number of the above type. 0 means first
    device_number = 1
    # OpenCL platform. -1 means automatic. Other numbers will index into list of platforms.
    platform_no = -1
    # Additional options given to the opencl compiler. See documentation for clBuildProgram
    compiler_flg = "-I/Users/mads/.bin/bohrium/share/bohrium/include"
    # List of extension methods
    libs = 
    # The pre-fuser to use
    pre_fuser = pre_fuser_lossy
    # List of instruction fuser/transformers
    fuser_list = greedy, push_reductions_inwards, split_for_threading, collapse_redundant_axes
    # Number of edges in the fusion graph that makes the greedy fuser use the `reshapable_first` fuser instead
    greedy_threshold = 10000
    # *_as_var specifies whether to hard-code variables or have them as variables
    index_as_var = true
    strides_as_var = true
    const_as_var = true
    # OpenCL work group sizes
    work_group_size_1dx = 128
    work_group_size_2dx = 32
    work_group_size_2dy = 4
    work_group_size_3dx = 32
    work_group_size_3dy = 2
    work_group_size_3dz = 2
    # Maximum number of threads to use (use 0 for infinity)
    num_threads = 0
    # Use round robin instead of block parallelization when limiting number of threads.
    num_threads_round_robin = false
    # Optimize instructions for GPU access (column-major)
    to_col_major = false

    [cuda]
    impl = /Users/mads/.bin/bohrium/lib/libbh_ve_cuda.dylib
    verbose = false
    # Profiling statistics
    prof = false
    prof_filename =
    # Write a Graphviz graph for each kernel
    graph = false
    # Directory for temporary files (e.g. /tmp/). Default: `boost::filesystem::temp_directory_path()`
    tmp_dir =
    # Directory for cache files (persistent between executions). Default: the empty string, which disable the cache
    cache_dir = /Users/mads/.bin/bohrium/var/bohrium/cache
    # Maximum number of cache files to keep in the cache dir (use -1 for infinity)
    cache_file_max = 50000
    # Set the size limit of malloc cache in percentage of total GPU memory.
    malloc_cache_limit = 90
    # The command to execute the compiler where {OUT} is replaced with the binary file output, {IN} with the source file,
    # and {CONF_PATH} with the path to this config file.
    # Additionally, {MAJOR} and {MINOR} are dynamically replaced with the compute capability version of the device
    compiler_cmd = "CUDA_NVCC_EXECUTABLE-NOTFOUND --cubin -m64 -arch=sm_{MAJOR}{MINOR} -O3 --disable-warnings -I/Users/mads/.bin/bohrium/share/bohrium/include {IN} -o {OUT}"
    # List of extension methods
    libs = 
    # The pre-fuser to use
    pre_fuser = pre_fuser_lossy
    # List of instruction fuser/transformers
    fuser_list = greedy, push_reductions_inwards, split_for_threading, collapse_redundant_axes
    # Number of edges in the fusion graph that makes the greedy fuser use the `reshapable_first` fuser instead
    greedy_threshold = 10000
    # *_as_var specifies whether to hard-code variables or have them as variables
    index_as_var = false
    strides_as_var = false
    const_as_var = false
    # CUDA work group sizes
    work_group_size_1dx = 128
    work_group_size_2dx = 32
    work_group_size_2dy = 4
    work_group_size_3dx = 32
    work_group_size_3dy = 2
    work_group_size_3dz = 2
    # Optimize instructions for GPU access (column-major)
    to_col_major = false
