### ISSUE TITLE
Wrong data type for BH_***_REDUCE functions?

### ISSUE THREAD

**Issue by Baekalfen** [bh107/bohrium#555]
This error doesn't seem to present itself on the master branch, but as I'm modifying Bohrium to run vector reduction through OpenCL, it seems to surface, as I want to find the identity element of the reduction.

In the file `core/codegen/opcodes.json`, `BH_MINIMUM_REDUCE` and the other reductions, are defined as using the parameters: `bool`, `bool`, `int64` or `float32`, `float32`, `int64`. This doesn't really make any sense, as reductions would mostly take two arguments of the same type, and output the same type.

I've tried changing the type the json, but then I'm met with some issues with `signature_hash` in `build/bridge/c/out/bhc_array_operations_enum_typed.cpp`, as it cannot match the type anymore.

Am I misunderstanding something, or is this a simple oversight?

**Comment by madsbk** [comment]
The last `BH_INT64` argument is the "axis" argument :)

**Comment by Baekalfen** [comment]
Ah, that makes sense. I guess I got confused because of the example with `BH_ADD` in `core/codegen/README` :)
