### ISSUE TITLE
TDMA extmethod not included in PyPI wheels

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#574]
The TDMA extmethod seems to be missing when `pip install`ing Bohrium (at least on OSX, maybe because of Clang vs. GCC?). I would suggest replacing it by a user kernel (e.g. the one from #572) to bring an end to the linking hell.

**Comment by dionhaefner** [comment]
Would you prefer to add the user kernel as a standin for `bh.linalg.solve_tridiagonal`, or just remove the function and add the user kernel to the docs (or some other independent collection of useful kernels)?

**Comment by dionhaefner** [comment]
Hmm, are you sure? There is no `np.linalg.solve_tridiagonal`, so this is a departure from the NumPy API. I think if we want to keep it we should document that more clearly?

For Veros I'm perfectly fine to have the tridiagonal solver in [two user kernels in the Veros repository](https://github.com/dionhaefner/veros/tree/userkernels/veros/core/special) (OpenMP and OpenCL). I don't think parallel solution of tridiagonal systems is a very common problem.

**Comment by madsbk** [comment]
I think it is okay to have extra functions compared to NumPy. But maybe we should put them into their own sub-module.
