### ISSUE TITLE
cpu_set_t not found when building on OSX

### ISSUE THREAD

**Issue by fjarri** [bh107/bohrium#7]
I'm trying to build Bohrium manually on OSX 10.10, and getting the following errors:

    [ 76%] Building CXX object vem/cluster/CMakeFiles/bh_vem_cluster.dir/pgrid.cpp.o
    /Users/bogdan/wb/repos/bohrium/vem/cluster/pgrid.cpp:87:9: error: unknown type name 'cpu_set_t'
            cpu_set_t cpuset;
            ^
    /Users/bogdan/wb/repos/bohrium/vem/cluster/pgrid.cpp:91:37: error: use of undeclared identifier
          'cpu_set_t'; did you mean 'cpuset'?
            sched_setaffinity(0, sizeof(cpu_set_t), &cpuset);
                                        ^~~~~~~~~
                                        cpuset
    /Users/bogdan/wb/repos/bohrium/vem/cluster/pgrid.cpp:87:19: note: 'cpuset' declared here
            cpu_set_t cpuset;
                      ^
    /Users/bogdan/wb/repos/bohrium/vem/cluster/pgrid.cpp:102:37: error: use of undeclared identifier
          'sched_getcpu'
                pgrid_myrank, hostname, sched_getcpu(), buf);
                                        ^

It seems that this structure should be defined in `bits/sched.h`, but I can't find this file on my system (or any other header with this definition). I followed the instructions from http://bohrium.readthedocs.org/installation/osx.html for manual installation. I'm open to any suggestions on how to debug this further.

**Comment by kenkendk** [comment]
I don't think the Cluster VEM compiles on OSX. At least I know that I have not tested it, and I do most of the OSX fixes.

Normally the build will just skip the Cluster VEM because MPI is not found.

Below is my output from cmake, does yours differ?

```
-- The following RECOMMENDED packages have been found:

 * OpenCL , Open Computing Language , <www.khronos.org/opencl/>
   Enables the GPU-VE.
 * NumPy , Numerical Python , <www.numpy.org>
   Enables the Python/NumPy bridge (together with Python and SWIG).
 * SWIG , Simplified Wrapper and Interface Generator , <www.swig.org>
   Enables the Python/NumPy bridge (together with Python and NumPy).
 * Cython , C-Extensions for Python , <cython.org>
   Enables the Python/NumPy bridge (together with Python and SWIG).
 * Mono , An open source implementation the CLR , <www.mono-project.com>
   Enables the NumCIL package

-- The following REQUIRED packages have been found:

 * Boost , Boost C++ source libraries , <www.boost.org>
   Boost is required to build Bohrium
 * Cheetah , Cheetah is a template module for Python , <www.cheetahtemplate.org>
   Cheetah is required to build Bohrium
 * GLUT
 * OpenGL , Open Graphics Library , <www.opengl.org>
   Required by OpenCL/GPU-VE.
 * PythonInterp , Python Programming Language , <www.python.org>
   Python is required to build Bohrium

-- The following OPTIONAL packages have not been found:

 * OpenMP

-- The following RECOMMENDED packages have not been found:

 * MPI , Message Passing Interface , <www.mpi-forum.org>
   Enables the Cluster-VEM.
 * FFTW , Fastest Fourier Transform in the West , <www.fftw.org>
   Enables the FFTW extended method
```

**Comment by fjarri** [comment]
That's what I have:

      -- The following RECOMMENDED packages have been found:

       * MPI , Message Passing Interface , <www.mpi-forum.org>
         Enables the Cluster-VEM.
       * OpenCL , Open Computing Language , <www.khronos.org/opencl/>
         Enables the GPU-VE.
       * OpenGL , Open Graphics Library , <www.opengl.org>
         Required by OpenCL/GPU-VE.
       * NumPy , Numerical Python , <www.numpy.org>
         Enables the Python/NumPy bridge (together with Python and SWIG).
       * SWIG , Simplified Wrapper and Interface Generator , <www.swig.org>
         Enables the Python/NumPy bridge (together with Python and NumPy).
       * Cython , C-Extensions for Python , <cython.org>
         Enables the Python/NumPy bridge (together with Python and SWIG).

      -- The following REQUIRED packages have been found:

       * Boost , Boost C++ source libraries , <www.boost.org>
         Boost is required to build Bohrium
       * Cheetah , Cheetah is a template module for Python , <www.cheetahtemplate.org>
         Cheetah is required to build Bohrium
       * PythonInterp , Python Programming Language , <www.python.org>
         Python is required to build Bohrium

      -- The following OPTIONAL packages have not been found:

       * OpenMP

      -- The following RECOMMENDED packages have not been found:

       * FFTW , Fastest Fourier Transform in the West , <www.fftw.org>
         Enables the FFTW extended method
         FFTW was found, but not enabled. 
         Manually enable FFTW with FFTW_INCLUDES and FFTW_LIBRARIES
         if you have a clang multi-arch FFTW binary.
       * Mono , An open source implementation the CLR , <www.mono-project.com>
         Enables the NumCIL package

So I do have MPI, but no OpenMP. I installed OpenMPI specifically for Bohrium via Homebrew, but I can remove it if it prevents the compilation — I don't use it otherwise.

**Comment by fjarri** [comment]
> I installed OpenMPI specifically for Bohrium via Homebrew, but I can remove it if it prevents the compilation

Actually, scratch that. I uninstalled openmpi from homebrew, and cmake is still able to find it.

**Comment by kenkendk** [comment]
In the folder where you checked out Bohrium, you should be able to do:

```
mkdir build
cd build
cmake -DVEM_CLUSTER=false ..
make install
```

Alternatively, you can use ``ccmake .`` to configure the build, and disable VEM_CLUSTER.

**Comment by fjarri** [comment]
Thanks, now the build passes. There's a (seemingly) related problem though: `import bohrium` passes, but when I try to use it, Python crashes with:

    Error in [node:impl]: dlopen(/Users/bogdan/.local/lib/libbh_vem_node.dylib, 2): Library not loaded: libbh.dylib
      Referenced from: /Users/bogdan/.local/lib/libbh_vem_node.dylib
      Reason: image not found

**Comment by kenkendk** [comment]
Try to clean out your install, i.e.:

```
rm -rf ~/.local/lib/libbh* ~/.local/var/bohrium ~/.bohrium
```

Then ```make install``` again.

If the file ```/Users/bogdan/.local/lib/libbh_vem_node.dylib``` exists, then it is most likely some issue with 64-vs-32 bit. You can see what version of Python you are running, with this snippet:

https://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit-mode-on-os

**Comment by fjarri** [comment]
I'm using Py2.7.9, using the tests from your link it's 64 bit. After removing everything and doing the clean install, the problem persists. The libraries in question seem to be multi-arch:

    > file /Users/bogdan/.local/lib/libbh_vem_node.dylib
    /Users/bogdan/.local/lib/libbh_vem_node.dylib: Mach-O universal binary with 2 architectures
    /Users/bogdan/.local/lib/libbh_vem_node.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
    /Users/bogdan/.local/lib/libbh_vem_node.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
    > file /Users/bogdan/.local/lib/libbh.dylib
    /Users/bogdan/.local/lib/libbh.dylib: Mach-O universal binary with 2 architectures
    /Users/bogdan/.local/lib/libbh.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
    /Users/bogdan/.local/lib/libbh.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64

By the way, why is there a "vem" library when I explicitly disabled it during compilation?

**Comment by kenkendk** [comment]
VEM stands for "Vector Engine Manager".
Currently there are two implementations of a VEM: Node and Cluster.
The Cluster VEM distributes (using MPI) work to multiple Node VEM's, which hands the work to the Vector Engine (VE).

So you get Python -> Bridge -> VEM -> VE.
Using the config.ini file you can change which VEM and VE you use, but you cannot skip the Node VEM (which, does not do anything but pass on the work).

I am trying a clean build to see if I can reproduce the issue.

**Comment by kenkendk** [comment]
I can reproduce. The problem is that when you are building from source, the install goes into `~/.local`.
On Linux the `~/.local/lib` folder is used automatically, but it is not on OSX.

To fix it, you need to set the environment variable `DYLD_LIBRARY_PATH`.

To set it, run:
```export DYLD_LIBRARY_PATH=~/.local/lib```

Or add it each time you run a command:
```DYLD_LIBRARY_PATH=~/.local/lib python ~/.local/share/bohrium/test/python/numpytest.py```

**Comment by fjarri** [comment]
Thank you, works now!
