### ISSUE TITLE
Bohrium fails to compile in the newest version (7568cc96db0ebe482ad3cb46e3028458b5f49f65)

### ISSUE THREAD

**Issue by Ektorus** [bh107/bohrium#8]
I have the following build options:
-- The following OPTIONAL packages have been found:
 * OpenMP

-- The following RECOMMENDED packages have been found:
 * HWLOC , hardware locality (hwloc) , <http://www.open-mpi.org/projects/hwloc/>
   VE-CPU use it to control thread affinity.
 * MPI , Message Passing Interface , <www.mpi-forum.org>
   Enables the Cluster-VEM.
 * FFTW , Fastest Fourier Transform in the West , <www.fftw.org>
   Enables the FFTW extended method
 * NumPy , Numerical Python , <www.numpy.org>
   Enables the Python/NumPy bridge (together with Python and SWIG).
 * SWIG , Simplified Wrapper and Interface Generator , <www.swig.org>
   Enables the Python/NumPy bridge (together with Python and NumPy).
 * Cython , C-Extensions for Python , <cython.org>
   Enables the Python/NumPy bridge (together with Python and SWIG).
 * Mono , An open source implementation the CLR , <www.mono-project.com>
   Enables the NumCIL package

-- The following REQUIRED packages have been found:
 * Boost , Boost C++ source libraries , <www.boost.org>
   Boost is required to build Bohrium
 * Cheetah , Cheetah is a template module for Python , <www.cheetahtemplate.org>
   Cheetah is required to build Bohrium
 * GLUT
 * OpenGL , Open Graphics Library , <www.opengl.org>
   Required by OpenCL/GPU-VE.
 * PythonInterp , Python Programming Language , <www.python.org>
   Python is required to build Bohrium

-- The following RECOMMENDED packages have not been found:
 * OpenCL , Open Computing Language , <www.khronos.org/opencl/>
   Enables the GPU-VE.

When I run make on the build files I get the following error:
/home/ulrik/git/bohrium/ve/cpu/utils_mapping_tacs.cpp: In function ‘void bohrium::core::instrs_to_tacs(bh_ir&, std::vector<tac>&, bohrium::core::Symbol
Table&)’:
/home/ulrik/git/bohrium/ve/cpu/utils_mapping_tacs.cpp:344:18: error: ‘BH_SIGN’ was not declared in this scope
             case BH_SIGN:
                  ^
ve/cpu/CMakeFiles/bh_ve_cpu.dir/build.make:238: recipe for target 've/cpu/CMakeFiles/bh_ve_cpu.dir/utils_mapping_tacs.cpp.o' failed
make[2]: *** [ve/cpu/CMakeFiles/bh_ve_cpu.dir/utils_mapping_tacs.cpp.o] Error 1
CMakeFiles/Makefile2:319: recipe for target 've/cpu/CMakeFiles/bh_ve_cpu.dir/all' failed
make[1]: *** [ve/cpu/CMakeFiles/bh_ve_cpu.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by madsbk** [comment]
It is because the introduction of BH_SIGN requires a "git clean -xdf" in some cases. 
NB: all non-committed files in your repos will be deleted!
